test_that("assert character", {
  expect_error(assertCharacter(1))
  expect_error(assertCharacter(list("hi")))
  expect_no_error(assertCharacter("hi"))
  expect_no_error(assertCharacter(c("hi", NA), na = TRUE))
  expect_error(assertCharacter(c("hi", NA), na = FALSE))
  expect_no_error(assertCharacter(c("hi"), length = 1))
  expect_error(assertCharacter(c("hi"), length = 2))
  expect_no_error(assertCharacter(NULL, null = TRUE))
  expect_error(assertCharacter(NULL, null = FALSE))
  expect_no_error(assertCharacter(c("hi", "hod"), named = FALSE))
  expect_error(assertCharacter(c("hi", "hod"), named = TRUE))
  expect_error(assertCharacter(c("hi", "x" = "hod"), named = TRUE))
  expect_no_error(assertCharacter(c(y = "hi", "x" = "hod"), named = TRUE))
  expect_no_error(assertCharacter(c(y = "hi", "x" = "hod"), minNumCharacter = 2))
  expect_no_error(assertCharacter(c(y = "hi", "x" = "hod"), minNumCharacter = 1))
  expect_error(assertCharacter(c(y = "hi", "x" = "hod"), minNumCharacter = 3))
})

test_that("assert logical", {
  expect_error(assertLogical("TRUE"))
  expect_no_error(assertLogical(TRUE))
  expect_no_error(assertLogical(c(T, NA), na = TRUE))
  expect_error(assertLogical(c(T, NA), na = FALSE))
  expect_no_error(assertLogical(T, length = 1))
  expect_error(assertLogical(T, length = 2))
  expect_no_error(assertLogical(NULL, null = TRUE))
  expect_error(assertLogical(NULL, null = FALSE))
  expect_no_error(assertLogical(c(F, T), named = FALSE))
  expect_error(assertLogical(c(F, T), named = TRUE))
  expect_error(assertLogical(c(T, "x" = F), named = TRUE))
  expect_no_error(assertLogical(c(y = T, "x" = F), named = TRUE))
})

test_that("assert numeric", {
  expect_error(assertNumeric("hi"))
  expect_no_error(assertNumeric(6))
  expect_error(assertNumeric(c(4.5), integerish = T))
  expect_error(assertNumeric(c(6, 4.5), integerish = T))
  expect_no_error(assertNumeric(c(4), integerish = T))
  expect_no_error(assertNumeric(c(4), min = 3))
  expect_error(assertNumeric(c(4), min = 5))
  expect_error(assertNumeric(c(4), max = 3))
  expect_no_error(assertNumeric(c(4), max = 5))
  expect_no_error(assertNumeric(c(6, NA), na = TRUE))
  expect_error(assertNumeric(c(6, NA), na = FALSE))
  expect_no_error(assertNumeric(6, length = 1))
  expect_error(assertNumeric(6, length = 2))
  expect_no_error(assertNumeric(NULL, null = TRUE))
  expect_error(assertNumeric(NULL, null = FALSE))
  expect_no_error(assertNumeric(c(4, 6), named = FALSE))
  expect_error(assertNumeric(c(4, 6), named = TRUE))
  expect_error(assertNumeric(c(4, "x" = 6), named = TRUE))
  expect_no_error(assertNumeric(c(y = 4, "x" = 6), named = TRUE))
})

test_that("assert list", {
  expect_error(assertList("hi"))
  expect_no_error(assertList(list("hi")))
  expect_no_error(assertList(list("hi", NA), na = TRUE))
  expect_error(assertList(list("hi", NA), na = FALSE))
  expect_no_error(assertList(list("hi"), length = 1))
  expect_error(assertList(list("hi"), length = 2))
  expect_no_error(assertList(NULL, null = TRUE))
  expect_error(assertList(NULL, null = FALSE))
  expect_no_error(assertList(list("hi", "hod"), named = FALSE))
  expect_error(assertList(list("hi", "hod"), named = TRUE))
  expect_error(assertList(list("hi", "x" = "hod"), named = TRUE))
  expect_no_error(assertList(list(y = "hi", "x" = "hod"), named = TRUE))
  expect_no_error(assertList(list(y = "4", "x" = "6"), named = TRUE, class = "character"))
  expect_error(assertList(list(y = "4", "x" = "6"), named = TRUE, class = "numeric"))
  expect_error(assertList(list(y = 4, "x" = 6), named = TRUE, class = "character"))
  expect_no_error(assertList(list(y = 4, "x" = 6), named = TRUE, class = "numeric"))
  expect_error(assertList(list(y = "4", "x" = 6), named = TRUE, class = "numeric"))
  expect_error(assertList(list(y = "4", "x" = 6), named = TRUE, class = "character"))
  expect_no_error(assertList(list(y = "4", "x" = "6"), named = TRUE, class = c("character", "numeric")))
  expect_no_error(assertList(list(y = 4, "x" = 6), named = TRUE, class = c("character", "numeric")))
  expect_no_error(assertList(list(y = "4", "x" = 6), named = TRUE, class = c("character", "numeric")))
})

test_that("assert tibble", {
  x <- dplyr::tibble(a = 1, b = 2, c = 3)
  expect_error(assertTibble("hi"))
  expect_no_error(assertTibble(x))
  expect_error(assertTibble(x, numberColumns = 5))
  expect_no_error(assertTibble(x, numberColumns = 3))
  expect_error(assertTibble(x, numberRows = 2))
  expect_no_error(assertTibble(x, numberRows = 1))
  expect_no_error(assertTibble(x, columns = c("a", "b")))
  expect_no_error(assertTibble(x, columns = c("a", "b", "c")))
  expect_error(assertTibble(x, columns = c("a", "b", "c", "d")))
  expect_no_error(assertTibble(NULL, null = TRUE))
  expect_error(assertTibble(NULL, null = FALSE))
})

test_that("assert choice", {
  expect_error(assertChoice("hi", c("a", "b")))
  expect_no_error(assertChoice("a", c("a", "b")))
  expect_no_error(assertChoice(c("a", "b"), c("a", "b")))
  expect_no_error(assertChoice("a", c("a", "b"), length = 1))
  expect_error(assertChoice("a", c("a", "b"), length = 2))
  expect_no_error(assertChoice(c("a", NA), c("a", "b"), na = T))
  expect_error(assertChoice(c("a", NA), c("a", "b"), na = F))
  expect_no_error(assertChoice(NULL, c("a", "b"), null = T))
  expect_error(assertChoice(NULL, c("a", "b"), null = F))
  expect_error(assertChoice(c("a" = "a", "b"), c("a", "b"), named = T))
  expect_no_error(assertChoice(c("a" = "a", "x" = "b"), c("a", "b"), named = T))
  expect_no_error(assertChoice(0, c(0, 1)))
  expect_error(assertChoice("0", c(0, 1)))
})
