test_that("assert character", {
  expect_no_error(assertCharacter("hi"))
  expect_no_error(assertCharacter(c("hi", NA), missing = TRUE))
  expect_error(assertCharacter(c("hi", NA), missing = FALSE))
  expect_no_error(assertCharacter(c("hi"), len = 1))
  expect_error(assertCharacter(c("hi"), len = 2))
  expect_no_error(assertCharacter(NULL, nullOk = TRUE))
  expect_error(assertCharacter(NULL, nullOk = FALSE))
  expect_no_error(assertCharacter(c("hi", "hod"), named = FALSE))
  expect_error(assertCharacter(c("hi", "hod"), named = TRUE))
  expect_error(assertCharacter(c("hi", "x" = "hod"), named = TRUE))
  expect_no_error(assertCharacter(c(y = "hi", "x" = "hod"), named = TRUE))
  expect_no_error(assertCharacter(c(y = "hi", "x" = "hod"), minNumCharacter = 2))
  expect_no_error(assertCharacter(c(y = "hi", "x" = "hod"), minNumCharacter = 1))
  expect_error(assertCharacter(c(y = "hi", "x" = "hod"), minNumCharacter = 3))
})
